development:
  adapter: mysql2
  encoding: utf8mb4
  database: medical
  pool: 5
  timeout: 5000
  host: localhost
  username: root     # use user/pass from local mysql set up
  password: abcd1234

production:
  adapter: mysql2
  encoding: utf8mb4
  database: medical
  pool: 5
  timeout: 5000
  host:  localhost
  port : 3306
  username: root     # use user/pass from local mysql set up
  password: 012_ighg
